constants:
  pathProduct: product.csv
  pathCard: card.csv
  pathInvalidFileName: invalidDate.txt
  fileName: check.txt
  allDiscount: 10


spring:
  liquibase:
    change-log: changeLog/createTest.sql
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  datasource:
    password: 18011984
    username: postgres
    url: jdbc:postgresql://localhost/postgres
    driver-class-name: org.postgresql.Driver

logging:
  log4j2:
    config:
      override: "src/main/resources/log4j2.xml"
